FROM maven:3.8.6-openjdk-11

RUN apt-get update \
    && apt-get upgrade -y

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
	&& apt-get update \
	&& apt-get -y install google-chrome-stable

WORKDIR /usr/src/project/My-2nd-expensive-Samsung-TV-Amazon

COPY . .

CMD mvn test


